apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    # Adding the quotes here is mandatory
    eks.amazonaws.com/role-arn: "{{ .Values.app.iam }}"