chip:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 0
  type: ClusterIP
green:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 0
  type: ClusterIP
kubernetesClusterDomain: cluster.local
